Repository takahirox/riscv-rust, pull requests merged in 2020-03, with the labels that each got.

#39 Skip redundant address translation
  src/mmu.rs
  src/wasm.rs
Labels: performance

#44 Implement CSRRC, CSRRCI, and CSRRSI instructions
  src/cpu.rs
Labels: enhancement

#48 RV64C
  src/cpu.rs
Labels: enhancement

#49 AMOADD_W
  src/cpu.rs
Labels: enhancement

#50 Add rustfmt.toml with hard_tabs set to true & run cargo fmt
  .rustfmt.toml
Labels: cleanup
